<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_cat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_cat_model');
    } 

    /*
     * Listing of product_cat
     */
    function index()
    {
        $data['product_cat'] = $this->Product_cat_model->get_all_product_cat();
        
        $data['_view'] = 'product_cat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product_cat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pcname' => $this->input->post('pcname'),
            );
            
            $product_cat_id = $this->Product_cat_model->add_product_cat($params);
            redirect('product_cat/index');
        }
        else
        {            
            $data['_view'] = 'product_cat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a product_cat
     */
    function edit($pcid)
    {   
        // check if the product_cat exists before trying to edit it
        $data['product_cat'] = $this->Product_cat_model->get_product_cat($pcid);
        
        if(isset($data['product_cat']['pcid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pcname' => $this->input->post('pcname'),
                );

                $this->Product_cat_model->update_product_cat($pcid,$params);            
                redirect('product_cat/index');
            }
            else
            {
                $data['_view'] = 'product_cat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product_cat you are trying to edit does not exist.');
    } 

    /*
     * Deleting product_cat
     */
    function remove($pcid)
    {
        $product_cat = $this->Product_cat_model->get_product_cat($pcid);

        // check if the product_cat exists before trying to delete it
        if(isset($product_cat['pcid']))
        {
            $this->Product_cat_model->delete_product_cat($pcid);
            redirect('product_cat/index');
        }
        else
            show_error('The product_cat you are trying to delete does not exist.');
    }
    
}
