<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sales extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 

    /*
     * Listing of product
     */
    function newsales()
    {
       $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'sales/newsales';
        $this->load->view('layouts/main',$data);
    }
    function invoicelist()
    {
       $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'sales/invoicelist';
        $this->load->view('layouts/main',$data);
    }
        
	function searchproduct(){
		$sql = "SELECT * from product WHERE product_name LIKE '%".$_GET['q']."%' LIMIT 10"; 
		$query=$this->db->query($sql);
		$rows=$query->result();
		foreach($rows as $row ){
			$productname=$row->product_code." : ".$row->product_name;
		 $json[] = ['product_id'=>$row->product_id, 'text'=>$row->product_name];
		}
		echo json_encode($json);
	}
	function addtocart(){
		$product_id = $_POST['product_id'];
		$quantity = $_POST['quantity'];
		$sql = "SELECT * from product WHERE product_id = $product_id"; 
		$query=$this->db->query($sql);
		$rows=$query->result();
		if($rows[0]){
		$catid=$rows[0]->product_cat;
		echo '<tr><th>'.$rows[0]->product_id.'</th><th>'.getcatname($catid).'</th><th>'.$rows[0]->product_code.'</th><th>'.$rows[0]->product_name.'</th><th><input style="width:100px;text-align:center" type="text" name="quantity[]" value="'.$quantity.'" /></th><th><input type="hidden" value="'.$rows[0]->product_id.'" name="pid[]" /><input style="width:100px;text-align:center" value="'.$rows[0]->price.'" type="text" name="price[]" /></th><th><a class="remove btn btn-info btn-xs">Remove</a></th></tr>';
		}
	}	
    function savesales(){
		$invoiceid=time();
		$userdata=$this->session->userdata();
		$userid=$userdata['userdata']->userid;
		$total=0;
		$pids=$_POST['pid'];
		$quantitys=$_POST['quantity'];
		$prices=$_POST['price'];
		$x=0;
		foreach($pids as $id){
			$qty=$quantitys[$x];
			$price=$prices[$x];
			$total=$total+$price;
			$this->db->query("UPDATE product SET quantity = quantity - $qty WHERE product_id = $id ");
			$salesdetails=array(
			'proid'=>$id,
			'qty'=>$qty,
			'price'=>$price,
			'invoiceid'=>$invoiceid
			);
			$this->db->insert('sales_details',$salesdetails);
			$x++;
		}
		
		$sales=array(
		'orderid'=>$_POST['orderid'],
		'cid'=>$_POST['cid'],
		'orderdate'=>$_POST['orderdate'],
		'invoiceid'=>$invoiceid,
		'invoicedate'=>date('Y-m-d'),
		'totalamount'=>$total,
		'salespersonid'=>'',
		'createdby'=>$userid		
		);
		$this->db->insert('sales',$sales);
		//redirect('stock/index');
		echo 'done';
	}
}
