<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
    } 

    /*
     * Listing of product
     */
    function index()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'stock/index';
        $this->load->view('layouts/main',$data);
    }
    function add()
    {
        $data['product'] = $this->Product_model->get_all_product();
        
        $data['_view'] = 'stock/stockadd';
        $this->load->view('layouts/main',$data);
    }
	function searchproduct(){
		$sql = "SELECT * from product WHERE product_name LIKE '%".$_GET['q']."%' LIMIT 10"; 
		$query=$this->db->query($sql);
		$rows=$query->result();
		foreach($rows as $row ){
			$productname=$row->product_code." : ".$row->product_name;
		 $json[] = ['product_id'=>$row->product_id, 'text'=>$row->product_name];
		}
		echo json_encode($json);
	}
	function addtocart(){
		$product_id = $_POST['product_id'];
		$quantity = $_POST['quantity'];
		$sql = "SELECT * from product WHERE product_id = $product_id"; 
		$query=$this->db->query($sql);
		$rows=$query->result();
		if($rows[0]){
		$catid=$rows[0]->product_cat;
		echo '<tr><th>'.$rows[0]->product_id.'</th><th>'.getcatname($catid).'</th><th>'.$rows[0]->product_code.'</th><th>'.$rows[0]->product_name.'</th><th><input style="width:100px;text-align:center" type="text" name="quantity[]" value="'.$quantity.'" /></th><th><input type="hidden" value="'.$rows[0]->product_id.'" name="pid[]" /><input style="width:100px;text-align:center" value="'.$rows[0]->price.'" type="text" name="price[]" /></th><th><a class="remove btn btn-info btn-xs">Remove</a></th></tr>';
		}
	}	
    function stockupdate(){		
		$pids=$_POST['pid'];
		$quantitys=$_POST['quantity'];
		$prices=$_POST['price'];
		$x=0;
		foreach($pids as $id){
			$qty=$quantitys[$x];
			$price=$prices[$x];
			$this->db->query("UPDATE product SET quantity = quantity + $qty WHERE product_id = $id ");
			$this->db->query("UPDATE product SET price = $price WHERE product_id = $id ");
			$x++;
		}
		redirect('stock/index');
	}
}
