<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer by customer_id
     */
    function get_customer($customer_id)
    {
        return $this->db->get_where('customer',array('customer_id'=>$customer_id))->row_array();
    }
        
    /*
     * Get all customer
     */
    function get_all_customer()
    {
        $this->db->order_by('customer_id', 'desc');
        return $this->db->get('customer')->result_array();
    }
        
    /*
     * function to add new customer
     */
    function add_customer($params)
    {
        $this->db->insert('customer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer
     */
    function update_customer($customer_id,$params)
    {
        $this->db->where('customer_id',$customer_id);
        return $this->db->update('customer',$params);
    }
    
    /*
     * function to delete customer
     */
    function delete_customer($customer_id)
    {
        return $this->db->delete('customer',array('customer_id'=>$customer_id));
    }
}
